version: '3'
services:
  mlflow:
    build: .
    ports:
      - "5000:5000"  # Exposer le port 5000 pour accéder à MLflow UI
    volumes:
      - .:/app  # Monter le répertoire actuel dans le conteneur
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
